### ISSUE TITLE
Add Support for Posix API's

### ISSUE THREAD

**Issue by sandeepmvd** [pelya/android-shmem#4]
Posix API's of shared memory (shm_open(), shm_unlink()) are not yet supported in this project. I think it is useful add the support. Are there any plans for it?

**Comment by pelya** [comment]
Nope. The purpose of this library was to speed up X server rendering, which
it does.

**Comment by sandeepmvd** [comment]
Ok. Thank you.
Since, we cannot specify the name in shmget(), the shmid received from shmget() should be passed among the processes. May I ask how are you actually passing shmid between the processes?

**Comment by pelya** [comment]
It uses libancillary, which uses Unix domain socket, special sendmsg()
call, and some dark magic, to pass a file descriptor between differerent
processes.

http://www.normalesup.org/~george/comp/libancillary/

**Comment by sandeepmvd** [comment]
Thank you. Sorry I think i did not explain my question correctly.

Consider the below scenario
Process 1 :
myshmid = shmget(...)
shmat(myshmid, ...)

Process 2
shmat(myshmid, ...)

In the above code myshmid in process1 and process 2 should be same. Therefore  "myshmid" generated by process 1 should be informed to process2 for calling shmat(). Only then the shared memory will work. My question was how did you transfer this shmid among the processes in your application that is using libandroid-shmem library? In my case I am using tmp files in /storage to transfer this information.

**Comment by pelya** [comment]
You communicate this ID between processes using any method. Temp files work
okay for this, X server transfers that ID to clients using TCP socket.

**Comment by sandeepmvd** [comment]
Ok. Thank you. It is working very well for me.
But In th logs it says the socket file is created in /dev/shm/ for example "shmat: addr /dev/shm/00000912"
But there is no such file present.. Although it is working well, this particular question is unclear for me.

**Comment by pelya** [comment]
It creates a named Unix socket, there is no file. You can see it with
netstat.

**Comment by sandeepmvd** [comment]
Thank you for clarification.
