### ISSUE TITLE
How to use this library for chroot?

### ISSUE THREAD

**Issue by Aloento** [pelya/android-shmem#9]
I try to used
env LD_PRELOAD=“/path/to/libandroid-shmem.so” chroot /rootfs /bin/su -l
But he told me, could not find the file or directory.
If I only use chroot /rootfs /bin/su -l ,will enter the system.
I am sure the library file directory is correct and given permission.
@pelya

**Comment by mgood7123** [comment]
it needs Android Dynamic Linker in order to be loaded (usually in /system/lib/linker or something)
